### Importing libraries and Loading Data

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import missingno as msno

In [ ]:
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)

In [ ]:
app_df = pd.read_csv('application_data.csv')

### Checking the Structure in the Data

In [ ]:
app_df.shape

In [ ]:
app_df.info()

In [ ]:
app_df.describe()

In [ ]:
# Using Missningno library to see the amount of null values in the data set 
msno.bar(app_df);

In [ ]:
# Let us sort the amount of Missing data in descending order
((app_df.isnull().sum()/len(app_df))*100).sort_values(ascending=False).head(51)

In [ ]:
app_df.shape

In [ ]:
# Let us drop the column with missing data more than 50%
drop_null = ((app_df.isnull().sum()/len(app_df))*100).sort_values(ascending=False)
app_df.drop(drop_null[drop_null>35].index,axis = 1,inplace = True)

In [ ]:
  # We dropped 49 columns
  app_df.shape

In [ ]:
# Let us fill the remaining null values by interpolating it.
# Interpolate = interpolate() function is basically used to fill NA values in the dataframe or series.
new_app_df = app_df.interpolate()

In [ ]:
msno.bar(new_app_df)

In [ ]:
new_app_df.isnull().sum().sort_values(ascending=False).head()

In [ ]:
new_app_df['OCCUPATION_TYPE'].fillna(new_app_df['OCCUPATION_TYPE'].mode()[0],inplace=True)
new_app_df['NAME_TYPE_SUITE'].fillna(new_app_df['NAME_TYPE_SUITE'].mode()[0],inplace=True)

In [ ]:
new_app_df.isnull().sum().sort_values(ascending=False).head()

In [ ]:
msno.bar(new_app_df);

The missing values have been delt with in the data set.

In [ ]:
# Cheking the Gender Column if any variable need to be replaced or not
new_app_df['CODE_GENDER'].value_counts()

In [ ]:
new_app_df['CODE_GENDER'] = new_app_df.CODE_GENDER.replace('XNA','M')

In [ ]:
new_app_df['CODE_GENDER'].value_counts()

# Checking of Outliers

In [ ]:
# Outlier of Organization
plt.figure(figsize=(10,8))
new_app_df['ORGANIZATION_TYPE'].value_counts().plot.box();

In [ ]:
# Outlier of Income column
# Using logarithmic value to convert the income columns
sns.boxplot(new_app_df['AMT_INCOME_TOTAL'])
print(new_app_df['AMT_INCOME_TOTAL'].describe())

In [ ]:
q1=new_app_df['AMT_INCOME_TOTAL'].describe()["25%"]
q3=new_app_df['AMT_INCOME_TOTAL'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['AMT_INCOME_TOTAL'] = np.where(new_app_df['AMT_INCOME_TOTAL']<lower_bound,lower_bound,new_app_df['AMT_INCOME_TOTAL'])
# Treating the outlier in the upper bound
new_app_df['AMT_INCOME_TOTAL'] = np.where(new_app_df['AMT_INCOME_TOTAL']>upper_bound,upper_bound,new_app_df['AMT_INCOME_TOTAL'])

In [ ]:
# Here the outlier can be seen more clearly in the Income column
plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['AMT_INCOME_TOTAL']);

In [ ]:
# AMT CREDIT column outlier
sns.boxplot(new_app_df['AMT_CREDIT'])
print(new_app_df['AMT_CREDIT'].describe())

In [ ]:
q1=new_app_df['AMT_CREDIT'].describe()["25%"]
q3=new_app_df['AMT_CREDIT'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['AMT_CREDIT'] = np.where(new_app_df['AMT_CREDIT']<lower_bound,lower_bound,new_app_df['AMT_CREDIT'])
# Treating the outlier in the upper bound
new_app_df['AMT_CREDIT'] = np.where(new_app_df['AMT_CREDIT']>upper_bound,upper_bound,new_app_df['AMT_CREDIT'])

plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['AMT_CREDIT']);

In [ ]:
# ANNUITY AMOUNT COLUMN OUTLIER
sns.boxplot(new_app_df['AMT_ANNUITY'])
print(new_app_df['AMT_ANNUITY'].describe())

In [ ]:
q1=new_app_df['AMT_ANNUITY'].describe()["25%"]
q3=new_app_df['AMT_ANNUITY'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['AMT_ANNUITY'] = np.where(new_app_df['AMT_ANNUITY']<lower_bound,lower_bound,new_app_df['AMT_ANNUITY'])
# Treating the outlier in the upper bound
new_app_df['AMT_ANNUITY'] = np.where(new_app_df['AMT_ANNUITY']>upper_bound,upper_bound,new_app_df['AMT_ANNUITY'])

plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['AMT_ANNUITY']);

In [ ]:
sns.boxplot(new_app_df['AMT_GOODS_PRICE'])
print(new_app_df['AMT_GOODS_PRICE'].describe())

In [ ]:
q1=new_app_df['AMT_GOODS_PRICE'].describe()["25%"]
q3=new_app_df['AMT_GOODS_PRICE'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['AMT_GOODS_PRICE'] = np.where(new_app_df['AMT_GOODS_PRICE']<lower_bound,lower_bound,new_app_df['AMT_GOODS_PRICE'])
# Treating the outlier in the upper bound
new_app_df['AMT_GOODS_PRICE'] = np.where(new_app_df['AMT_GOODS_PRICE']>upper_bound,upper_bound,new_app_df['AMT_GOODS_PRICE'])

plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['AMT_GOODS_PRICE']);

In [ ]:
sns.boxplot(new_app_df['EXT_SOURCE_3'])
print(new_app_df['EXT_SOURCE_3'].describe())

In [ ]:
#Checking the days column if there is any negative values
[i for i in new_app_df if i.startswith('DAYS')]
print(new_app_df.DAYS_BIRTH.unique())
print(new_app_df.DAYS_EMPLOYED.unique())
print(new_app_df.DAYS_REGISTRATION.unique())
print(new_app_df.DAYS_ID_PUBLISH.unique())
print(new_app_df.DAYS_LAST_PHONE_CHANGE.unique())

In [ ]:
# Since days cannot be negative let us replace those negative columns
# Let us use abs function to convert the negative values
error_col = [i for i in new_app_df if i.startswith('DAYS')]
new_app_df[error_col] = abs(new_app_df[error_col])
print(new_app_df.DAYS_BIRTH.unique())
print(new_app_df.DAYS_EMPLOYED.unique())
print(new_app_df.DAYS_REGISTRATION.unique())
print(new_app_df.DAYS_ID_PUBLISH.unique())
print(new_app_df.DAYS_LAST_PHONE_CHANGE.unique())

In [ ]:
sns.boxplot(new_app_df['DAYS_BIRTH'])
print(new_app_df['DAYS_BIRTH'].describe())

In [ ]:
sns.boxplot(new_app_df['DAYS_EMPLOYED'])
print(new_app_df['DAYS_EMPLOYED'].describe())

In [ ]:
q1=new_app_df['DAYS_EMPLOYED'].describe()["25%"]
q3=new_app_df['DAYS_EMPLOYED'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['DAYS_EMPLOYED'] = np.where(new_app_df['DAYS_EMPLOYED']<lower_bound,lower_bound,new_app_df['DAYS_EMPLOYED'])
# Treating the outlier in the upper bound
new_app_df['DAYS_EMPLOYED'] = np.where(new_app_df['DAYS_EMPLOYED']>upper_bound,upper_bound,new_app_df['DAYS_EMPLOYED'])

plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['DAYS_EMPLOYED']);

In [ ]:
sns.boxplot(new_app_df['DAYS_REGISTRATION'])
print(new_app_df['DAYS_REGISTRATION'].describe())

In [ ]:
q1=new_app_df['DAYS_REGISTRATION'].describe()["25%"]
q3=new_app_df['DAYS_REGISTRATION'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['DAYS_REGISTRATION'] = np.where(new_app_df['DAYS_REGISTRATION']<lower_bound,lower_bound,new_app_df['DAYS_REGISTRATION'])
# Treating the outlier in the upper bound
new_app_df['DAYS_REGISTRATION'] = np.where(new_app_df['DAYS_REGISTRATION']>upper_bound,upper_bound,new_app_df['DAYS_REGISTRATION'])

plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['DAYS_REGISTRATION']);

In [ ]:
sns.boxplot(new_app_df['DAYS_ID_PUBLISH'])
print(new_app_df['DAYS_ID_PUBLISH'].describe())

In [ ]:
sns.boxplot(new_app_df['DAYS_LAST_PHONE_CHANGE'])
print(new_app_df['DAYS_LAST_PHONE_CHANGE'].describe())

In [ ]:
q1=new_app_df['DAYS_LAST_PHONE_CHANGE'].describe()["25%"]
q3=new_app_df['DAYS_LAST_PHONE_CHANGE'].describe()["75%"]
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
# Treating the outlier in the lower bound
new_app_df['DAYS_LAST_PHONE_CHANGE'] = np.where(new_app_df['DAYS_LAST_PHONE_CHANGE']<lower_bound,lower_bound,new_app_df['DAYS_LAST_PHONE_CHANGE'])
# Treating the outlier in the upper bound
new_app_df['DAYS_LAST_PHONE_CHANGE'] = np.where(new_app_df['DAYS_LAST_PHONE_CHANGE']>upper_bound,upper_bound,new_app_df['DAYS_LAST_PHONE_CHANGE'])

plt.figure(figsize=(10,8))
sns.boxplot(new_app_df['DAYS_LAST_PHONE_CHANGE']);

## DATA IMBALANCE

In [ ]:
new_app_df['TARGET'].value_counts(normalize=True)*100

## SEGMENTED UNIVARIATE ANALYSIS

In [ ]:
target_0 = new_app_df[new_app_df['TARGET']==0]
target_1 = new_app_df[new_app_df['TARGET']==1]

In [ ]:
plt.figure(figsize=(12,9))
sns.countplot(round(new_app_df['TARGET'].value_counts(normalize=True)*100,2));

In [ ]:
# Income Total:Target_0
plt.figure(figsize = (11,8))
sns.histplot(target_0['AMT_INCOME_TOTAL'],bins = [i for i in range(0,1000000,50000)]);

In [ ]:
# Income Column : Target_1
plt.figure(figsize = (11,8))
sns.histplot(target_1['AMT_INCOME_TOTAL'],bins =[i for i in range(0,1000000,50000)]);

In [ ]:
# Annuity column : Target 0
plt.figure(figsize = (11,8))
sns.histplot(target_0['AMT_ANNUITY'],bins =[i for i in range(0,1000000,50000)]);

In [ ]:
# Annuity column : Target 1
plt.figure(figsize = (11,8))
sns.histplot(target_1['AMT_ANNUITY'],bins =[i for i in range(0,1000000,50000)]);

### Let us bin continous variables

In [ ]:
# Binning of Income category
new_app_df['Income_Category'] = pd.qcut(new_app_df.AMT_INCOME_TOTAL.rank(method='first'),q = [0,0.2,0.5,0.8,0.95,1],
                                   labels = ['Very Low','Low','Midium','High','Very High'])

In [ ]:
new_app_df['Income_Category'].head()

In [ ]:
plt.figure(figsize = (11,8))
sns.countplot(new_app_df['Income_Category']);

In [ ]:
# Binning Birth days columns
new_app_df.DAYS_BIRTH = (new_app_df.DAYS_BIRTH / 365).astype(int)
new_app_df['AGE_BINS'] = pd.cut(new_app_df['DAYS_BIRTH'],bins=[19,25,35,60,100],labels = ['Adolescent','Young','Middile Age','Senior Citizen'])

In [ ]:
new_app_df['AGE_BINS'].value_counts()

In [ ]:
plt.figure(figsize = (11,8))
sns.countplot(new_app_df['AGE_BINS']);

In [ ]:
new_app_df['Credit_Category'] = pd.qcut(new_app_df.AMT_CREDIT,q = [0,0.2,0.5,0.8,0.95,1],
                                 labels = ['Very Low','Low','Midium','High','Very High'])

In [ ]:
new_app_df['Credit_Category'].head()

In [ ]:
plt.figure(figsize=(11,8))
sns.countplot(new_app_df['Credit_Category']);

In [ ]:
new_app_df.info()

In [ ]:
# Let us drop the flag column since most of the customer or client fullfill its requirement and is 0
flag_column_drop = new_app_df.iloc[:,47:67]
new_app_df.shape
new_app_df.drop(flag_column_drop,axis=1,inplace=True)
new_app_df.shape

In [ ]:
import cufflinks
cufflinks.go_offline()
cufflinks.set_config_file(world_readable=True)

In [ ]:
# DIVIDING THE DATASET IN TARGET 0 AND 1 
target_0 = new_app_df[new_app_df['TARGET']==0]
target_1 = new_app_df[new_app_df['TARGET']==1]

In [ ]:
# Income Column: Target 0 
income_tar = target_0['NAME_INCOME_TYPE'].value_counts(normalize = True)
income_df = pd.DataFrame({'labels':income_tar.index,'values':income_tar})
income_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Income source of Non Payment difficulties of Client',hole=0.8)

In [ ]:
# Income Column: Target 1 
income_tar = target_1['NAME_INCOME_TYPE'].value_counts(normalize = True)
income_df = pd.DataFrame({'labels':income_tar.index,'values':income_tar})
income_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Income source of  Payment difficulties of Client',hole=0.8)

In [ ]:
#Occupation: Target 0
occupation_tar = target_0['OCCUPATION_TYPE'].value_counts(normalize = True)
occupation_df = pd.DataFrame({'labels':occupation_tar.index,'values':occupation_tar})
occupation_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Occupation of Client Target 0',hole=0.8)

In [ ]:
# Occupation Target 1
occupation_tar = target_1['OCCUPATION_TYPE'].value_counts(normalize = True)
occupation_df = pd.DataFrame({'labels':occupation_tar.index,'values':occupation_tar})
occupation_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Occupation of Client Target 1',hole=0.8);

In [ ]:
# Gender : Target 0
gender_tar = target_0['CODE_GENDER'].value_counts(normalize = True)
gender_tar = pd.DataFrame({'labels':gender_tar.index,'values':gender_tar})
gender_tar.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Gender Target 0 clients',hole=0.8)

In [ ]:
# Gender : Target 1
gender_tar = target_1['CODE_GENDER'].value_counts(normalize = True)
gender_df = pd.DataFrame({'labels':gender_tar.index,'values':gender_tar})
gender_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Gender Target 1 clients ',hole=0.8)

In [ ]:
# Organization Type: Target 0
organization_tar = target_0['ORGANIZATION_TYPE'].value_counts(normalize = True)
org_df= pd.DataFrame({'labels':organization_tar.index,'values':organization_tar})
org_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Oragnization Target 0 clients ',hole=0.8)

In [ ]:
# Organization: Target 1 
org_tar = target_1['ORGANIZATION_TYPE'].value_counts(normalize = True)
org_df = pd.DataFrame({'labels':org_tar.index,'values':org_tar})
org_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Organiztion Target 1 clients ',hole=0.8)

In [ ]:
#  Goods Price Columns: Distribution of Target 0
plt.figure(figsize=(11,8))
plt.title('Target 0 AMT_GOODS_PRICE')
sns.distplot(target_0['AMT_GOODS_PRICE']);

In [ ]:
#  Goods Price Columns: Distribution of Target 1
plt.figure(figsize=(11,8))
plt.title('Target 1 AMT_GOODS_PRICE')
sns.distplot(target_1['AMT_GOODS_PRICE']);

In [ ]:
#  Education : Target 0
edu_tar = target_0['NAME_EDUCATION_TYPE'].value_counts(normalize = True)
edu_df= pd.DataFrame({'labels':edu_tar.index,'values':edu_tar})
edu_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Education Target 0 clients ',hole=0.8)

In [ ]:
# Education : Target 1
edu_tar = target_1['NAME_EDUCATION_TYPE'].value_counts(normalize = True)
edu_df= pd.DataFrame({'labels':edu_tar.index,'values':edu_tar})
edu_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Education Target 1 clients ',hole=0.8)

In [ ]:
#  Contract type : Target 0
contract_tar = target_0['NAME_CONTRACT_TYPE'].value_counts(normalize = True)
contract_df= pd.DataFrame({'labels':contract_tar.index,'values':contract_tar})
contract_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Contract Target 0 clients ',hole=0.8)

In [ ]:
#  Contract type : Target 1
contract_tar = target_1['NAME_CONTRACT_TYPE'].value_counts(normalize = True)
contract_df= pd.DataFrame({'labels':contract_tar.index,'values':contract_tar})
contract_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Contract Target 1 clients ',hole=0.8)

In [ ]:
#   Own Car : Target 0
car_tar = target_0['FLAG_OWN_CAR'].value_counts(normalize = True)
car_df= pd.DataFrame({'labels':car_tar.index,'values':car_tar})
car_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Own Car Target 0 clients ',hole=0.8)

In [ ]:
#   Own Car : Target 1
car_tar = target_1['FLAG_OWN_CAR'].value_counts(normalize = True)
car_df= pd.DataFrame({'labels':car_tar.index,'values':car_tar})
car_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Own Car Target 1 clients ',hole=0.8)

In [ ]:
#   Realty : Target 0
realty_tar = target_0['FLAG_OWN_REALTY'].value_counts(normalize = True)
realty_df= pd.DataFrame({'labels':realty_tar.index,'values':realty_tar})
realty_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Realty Target 0 clients ',hole=0.8)

In [ ]:
#   Realty : Target 1
realty_tar = target_1['FLAG_OWN_REALTY'].value_counts(normalize = True)
realty_df= pd.DataFrame({'labels':realty_tar.index,'values':realty_tar})
realty_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Realty Target 1 clients ',hole=0.8)

In [ ]:
#   Suit : Target 0
suit_tar = target_0['NAME_TYPE_SUITE'].value_counts(normalize = True)
suit_df= pd.DataFrame({'labels':suit_tar.index,'values':suit_tar})
suit_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Suit Target 0 clients ',hole=0.8)

In [ ]:
#   Suit : Target 1
suit_tar = target_1['NAME_TYPE_SUITE'].value_counts(normalize = True)
suit_df= pd.DataFrame({'labels':suit_tar.index,'values':suit_tar})
suit_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Suit Target 1 clients ',hole=0.8)

In [ ]:
#   Family Status : Target 0
family_status_tar = target_0['NAME_FAMILY_STATUS'].value_counts(normalize = True)
family_status_df= pd.DataFrame({'labels':family_status_tar.index,'values':family_status_tar})
family_status_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Family Status Target 0 clients ',hole=0.8)

In [ ]:
#   Family Status : Target 1
family_status_tar = target_1['NAME_FAMILY_STATUS'].value_counts(normalize = True)
family_status_df= pd.DataFrame({'labels':family_status_tar.index,'values':family_status_tar})
family_status_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Family Status Target 1 clients ',hole=0.8)

In [ ]:
#   House Type : Target 0
House_type_tar = target_0['NAME_HOUSING_TYPE'].value_counts(normalize = True)
House_type_df= pd.DataFrame({'labels':House_type_tar.index,'values':House_type_tar})
House_type_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Own House Type Target 0 clients ',hole=0.8)

In [ ]:
#   House Type : Target 1
House_type_tar = target_1['NAME_HOUSING_TYPE'].value_counts(normalize = True)
House_type_df= pd.DataFrame({'labels':House_type_tar.index,'values':House_type_tar})
House_type_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Own House Type Target 1 clients ',hole=0.8)

In [ ]:
#  Application Process : Target 0
application_process_tar = target_0['WEEKDAY_APPR_PROCESS_START'].value_counts(normalize = True)
application_process_df= pd.DataFrame({'labels':application_process_tar.index,'values':application_process_tar})
application_process_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Application Process Target 0 clients ',hole=0.8)

In [ ]:
#  Application Process : Target 1
application_process_tar = target_1['WEEKDAY_APPR_PROCESS_START'].value_counts(normalize = True)
application_process_df= pd.DataFrame({'labels':application_process_tar.index,'values':application_process_tar})
application_process_df.iplot(kind='pie',labels = 'labels',values = 'values',title = 'Application Process Target 1 clients ',hole=0.8)

## Bivariate Analysis and Multivariate analysis

In [ ]:
# CREDIT VS GOODS PRICE : TARGET 0
sns.jointplot(data=target_0, x='AMT_CREDIT', y='AMT_GOODS_PRICE')
plt.xlabel('Loan Amount')
plt.ylabel('Goods price');

In [ ]:
# CREDIT VS GOODS PRICE : TARGET 1
sns.jointplot(data=target_1, x='AMT_CREDIT', y='AMT_GOODS_PRICE')
plt.xlabel('Loan Amount')
plt.ylabel('Goods price');

In [ ]:
sns.displot(target_0, x="AMT_CREDIT", hue="Income_Category", kind="kde", fill=True);

In [ ]:
sns.displot(target_1, x="AMT_CREDIT", hue="Income_Category", kind="kde", fill=True);

In [ ]:
plt.figure(figsize = (12,8))
sns.displot(target_0, x="AMT_CREDIT", y="AMT_INCOME_TOTAL", kind="kde");

In [ ]:
plt.figure(figsize = (12,8))
sns.displot(target_1, x="AMT_CREDIT", y="AMT_INCOME_TOTAL", kind="kde");

In [ ]:
#education and income target 1 and 0
plt.figure(figsize = (12,8))
sns.displot(target_0, x="AMT_INCOME_TOTAL", hue="NAME_EDUCATION_TYPE", kind="kde", fill=True);

In [ ]:
plt.figure(figsize = (12,8))
sns.displot(target_1, x="AMT_INCOME_TOTAL", hue="NAME_EDUCATION_TYPE", kind="kde", fill=True);

In [ ]:
# education  and credit target 1 and 0
plt.figure(figsize = (12,8))
sns.displot(target_0, x="AMT_CREDIT", hue="NAME_EDUCATION_TYPE", kind="kde", fill=True);

In [ ]:
plt.figure(figsize = (12,8))
sns.displot(target_1, x="AMT_CREDIT", hue="NAME_EDUCATION_TYPE", kind="kde", fill=True);

In [ ]:
sns.displot(target_0, x="AMT_CREDIT", hue="NAME_HOUSING_TYPE", kind="kde", fill=True);

In [ ]:
sns.displot(target_1, x="AMT_CREDIT", hue="NAME_HOUSING_TYPE", kind="kde", fill=True);

In [ ]:
sns.displot(target_0, x="AMT_INCOME_TOTAL", hue="NAME_CONTRACT_TYPE", kind="kde", fill=True);

In [ ]:
sns.displot(target_1, x="AMT_INCOME_TOTAL", hue="NAME_CONTRACT_TYPE", kind="kde", fill=True);

In [ ]:
# Occupation vs Organization vs Credit : Target 0
res = pd.pivot_table(data = target_0, index = 'OCCUPATION_TYPE',columns = 'ORGANIZATION_TYPE',values = 'AMT_CREDIT')
res

In [ ]:
plt.figure(figsize=(11,9))
sns.heatmap(res,cmap = 'Blues',center = 0.117);

In [ ]:
# Occupation vs Organization vs Credit : Target 1
res = pd.pivot_table(data = target_1, index = 'OCCUPATION_TYPE',columns = 'ORGANIZATION_TYPE',values = 'AMT_CREDIT')
res

In [ ]:
plt.figure(figsize=(11,9))
sns.heatmap(res,cmap = 'Greens',center = 0.117);

In [ ]:
# Occupation vs Organization vs Income total : Target 0
res = pd.pivot_table(data = target_0, index = 'OCCUPATION_TYPE',columns = 'ORGANIZATION_TYPE',values = 'AMT_INCOME_TOTAL')
res

In [ ]:
plt.figure(figsize=(11,9))
sns.heatmap(res,cmap = 'Blues',center = 0.117);

In [ ]:
plt.figure(figsize = (12,8))
sns.heatmap(
    target_0.loc[:,['CNT_CHILDREN','REGION_POPULATION_RELATIVE','AMT_INCOME_TOTAL','AMT_CREDIT','AMT_ANNUITY','AMT_GOODS_PRICE','DAYS_EMPLOYED','AGE_BINS']].corr(),
    annot=True,
    cmap = 'Blues'
);

In [ ]:
plt.figure(figsize = (12,8))
sns.heatmap(
    target_1.loc[:,['CNT_CHILDREN','REGION_POPULATION_RELATIVE','AMT_INCOME_TOTAL','AMT_CREDIT','AMT_ANNUITY','AMT_GOODS_PRICE','DAYS_EMPLOYED','AGE_BINS']].corr(),
    annot=True,
    cmap = 'Greens'
);

## Insights from the application dataset
We can see from the datasets that there are a number of criteria that the bank can use to determine who can repay the loan.

# Factors of non defaulters are:
1. LOANS EDUCATION TYPE: People with academic degrees had fewer defaults than the general population.
2. NAME INCOME TYPE: There are no presets for students or businesspeople.
3. Widows are the least likely to default on their loans, according to NAME FAMILY STATUS.
4. AMT INCOME TOTAL: Customers with incomes between 700,000 and 800,000 are the least likely to default.
5. Clients with Trade Types 4 and 6 and Industry Type 12 ORGANIZATION TYPE: Type 1 vehicles are the least prone to default.

## Factors of Defaulters:

1. CODE GENDER: Male customers are more likely than female customers to default on their payments.

2. NAME FAMILY STATUS: Single people and those who have married civilly are more prone to default.

3. NAME INCOME TYPE: Clients on maternity leave or who are unemployed are more prone to miss payments.

4. People who live in rented flats or with their parents are more likely to default on their loans.

5. Low-skilled labourers are the most prone to fail on their loans.

6. AGE GROUP: Those between the ages of 20 and 40 are the most likely to fail on a loan.

In [ ]:
# write the insights

In [ ]:
prev_app_df = pd.read_csv('previous_application.csv')

In [ ]:
prev_app_df.info()

In [ ]:
msno.dendrogram(prev_app_df);

In [ ]:
msno.bar(prev_app_df);

In [ ]:
prev_app_df.shape

In [ ]:
drop_null = ((prev_app_df.isnull().sum()/len(prev_app_df))*100).sort_values(ascending=False)
prev_app_df.drop(drop_null[drop_null>35].index,axis = 1,inplace = True)

In [ ]:
prev_app_df.shape

In [ ]:
# let us fill up the null values
prev_app_df = prev_app_df.interpolate()

In [ ]:
msno.bar(prev_app_df);

In [ ]:
# Let us merge the application and previous dataset
merge_df = pd.merge(new_app_df,prev_app_df,on = 'SK_ID_CURR',how = 'inner')

In [ ]:
merge_df.info()

In [ ]:
merge_df.shape

In [ ]:
# renaming the merged data set
merge_df.rename({'NAME_CONTRACT_TYPE_x':'NAME_CONTRACT_TYPE_APP','AMT_CREDIT_x':'AMT_CREDIT_APP', 
'AMT_ANNUITY_x':'AMT_ANNUITY_APP', 'AMT_GOODS_PRICE_x':'AMT_GOODS_PRICE_APP',
'WEEKDAY_APPR_PROCESS_START_x':'WEEKDAY_APPR_PROCESS_START_APP', 'HOUR_APPR_PROCESS_START_x':'HOUR_APPR_PROCESS_START_APP',
'NAME_CONTRACT_TYPE_y':'NAME_CONTRACT_TYPE_PRV', 'AMT_ANNUITY_y':'AMT_ANNUITY_PRV',
'AMT_CREDIT_y':'AMT_CREDIT_PRV', 'AMT_GOODS_PRICE_y':'AMT_GOODS_PRICE_PRV',
'WEEKDAY_APPR_PROCESS_START_y':'WEEKDAY_APPR_PROCESS_START_PRV', 'HOUR_APPR_PROCESS_START_y':'HOUR_APPR_PROCESS_START_PRV'}, axis=1, inplace=True)

In [ ]:
merge_df.info()

In [ ]:
plt.figure(figsize=[12,8])
payment_df = merge_df.NAME_PAYMENT_TYPE.value_counts(normalize=True).to_frame(name='Loan Applications')
sns.barplot(data=payment_df, y=payment_df.index, x=payment_df['Loan Applications'],orient='h').set(ylabel = 'Payment Types', title ='Payment Types Vs  Loan Applications');

In [ ]:
# Visulizing Graph according to Target Client 0 and 1
# Target 0 = Non Defaulters
# Target 1 = Defaulters
target_df_0 = merge_df[merge_df['TARGET']==0] 
target_df_1 = merge_df[merge_df['TARGET']==1]

In [ ]:
sns.pairplot(data = target_df_0,vars=['AMT_INCOME_TOTAL',
 'AMT_CREDIT_APP',
 'AMT_ANNUITY_APP',
 'AMT_GOODS_PRICE_APP',
 'AGE_BINS']);

In [ ]:
sns.pairplot(data = target_df_1,vars=['AMT_INCOME_TOTAL',
 'AMT_CREDIT_APP',
 'AMT_ANNUITY_APP',
 'AMT_GOODS_PRICE_APP',
 'AGE_BINS']);

In [ ]:
plt.figure(figsize = (12,8))
sns.countplot(x = 'NAME_CASH_LOAN_PURPOSE',data = merge_df,hue = 'NAME_CONTRACT_STATUS',log=True)
plt.xticks(rotation = 90);

In [ ]:
# Defaulters
plt.figure(figsize = (12,8))
sns.countplot(x = 'NAME_CASH_LOAN_PURPOSE',data = target_df_0,hue = 'NAME_CONTRACT_STATUS',log=True)
plt.xticks(rotation = 90);

In [ ]:
# Non Defaulters
plt.figure(figsize = (12,8))
sns.countplot(x = 'NAME_CASH_LOAN_PURPOSE',data = target_df_1,hue = 'NAME_CONTRACT_STATUS',log=True)
plt.xticks(rotation = 90);

In [ ]:
plt.figure(figsize=(12,8))
sns.countplot(data = merge_df,x='NAME_CONTRACT_STATUS',hue = 'TARGET')
plt.legend(['NON-DEFAULTERS','DEFAULTERS']);

In [ ]:
def bar_graph(df, y_label, x_label, hue_value, title, orien, width, length, scale):
    plt.figure(figsize=(width,length))
    plt.xticks(rotation=90)
    if scale == 'xscale':
        plt.xscale('log')
    else:
        plt.yscale('log')
    sns.barplot(data =merge_df, y=y_label, hue=hue_value, x=x_label, errwidth=0, orient= orien)
    plt.title(title);

In [ ]:
bar_graph(merge_df, 'AMT_CREDIT_PRV', 'NAME_INCOME_TYPE', 'CODE_GENDER', 'LAST YEAR CREDIT vs HOUSE TYPE', 'v', 16, 12, 'yscale')

In [ ]:
bar_graph(merge_df,'AMT_APPLICATION','NAME_EDUCATION_TYPE', 'NAME_CONTRACT_STATUS', 'APPLICATION AMOUNT vs EDUCATIONAL BACKGROUND', 'v', 18,12, 'yscale')

In [ ]:
corr_df = merge_df[['AMT_INCOME_TOTAL',
       'AMT_CREDIT_APP', 'AMT_ANNUITY_APP', 'AMT_GOODS_PRICE_APP','CNT_CHILDREN','CNT_FAM_MEMBERS','AGE_BINS','AMT_APPLICATION','AMT_ANNUITY_PRV',
        'AMT_CREDIT_PRV', 'AMT_GOODS_PRICE_PRV','NAME_HOUSING_TYPE']].corr()
corr_df

In [ ]:
plt.figure(figsize=[24, 10])

sns.heatmap(annot= True, data=corr_df ,cmap='Blues');

According to the heatmap above, there is a strong correlation between the Goods Price and the Loan Amount of the currently credited application. Furthermore, there is a strong link between the Loan Amount requested by the applicant and the Loan Amount credited in the previous application.

However, there is a weak correlation between age and the number of children, as well as between the Goods price for the loan, the loan amount credited, and the loan anuity of the current and previous application.

The following variables indicate that people in the following categories are more likely to default on a loan, which can be avoided by giving them loans with a higher interest rate to cushion any default risk and, as a result, avoid any business loss:

NAME HOUSING TYPE: People who live in Rented Apartments take a lot of loans, but they also fail more frequently. As a result, turning them off totally would be a financial loss.

AMT CREDIT: People earning between $100,000 and 200,000 have a greater default rate than those earning less than 100,000. So it would make sense to keep the interest rate higher.

NAME EDUCATION TYPE: People with a secondary or special education applied for the majority of loans, therefore maintaining a low interest rate for them would be beneficial to the business.

NAME CASH LOAN PURPOSE: Loans obtained for the purpose of repairs have a higher default rate, and as a result, the bank charges a higher interest rate to that customer, which the client cannot handle, and therefore the loan is cancelled at later stages of the application.

OCCUPATION TYPE: Many low-skilled and other labourers apply for loans, and they have a higher default rate. Given that these individuals have low incomes, the bank should maintain a reasonable interest rate that will prevent these individuals from defaulting.